def exceptionTestcases():
    print('hello')
    return
